import Navbar from "@/src/components/Navbar";

import "../style/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                var script = document.createElement('script');
                script.type = 'text/javascript';
                script.src = '//script.crazyegg.com/pages/scripts/0127/8659.js';
                script.fetchPriority = 'high';
                document.head.appendChild(script);
              })();
            `,
          }}
        ></script>
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
