import Navbar from "@/src/components/Navbar";
import React, { useEffect } from "react";
import "../style/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <link rel="preload" href="/style/globals.css" as="style" />
        <script
          type="text/javascript"
          src="//script.crazyegg.com/pages/scripts/0127/9507.js"
          defer
        ></script>
      </head>
      <body>
        <main id="ab-content">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
