"use client"
import Navbar from "@/src/components/Navbar";
import Script from "next/script"; // Use Next.js Script component
import React, { useState, useEffect } from "react";
import "../style/globals.css";

declare global {
  interface Window {
    CE2: any;
  }
}

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isVariantReady, setIsVariantReady] = useState(false);
// console.log(window?.CE2?.LOADED_SCRIPTS,"window.CE2");

  useEffect(() => {
    const checkCrazyEgg = () => {
      // Example: Detect Crazy Egg or variant readiness
      if (window.CE2) {
        setIsVariantReady(true);
      } else {
        setTimeout(checkCrazyEgg, 100); // Retry until Crazy Egg is ready
      }
    };

    checkCrazyEgg();
  }, []);

  return (
    <html lang="en">
      <head>
        {/* Crazy Egg Script */}
        <Script
          src="//script.crazyegg.com/pages/scripts/0127/8659.js"
          strategy="afterInteractive"
          onLoad={() => console.log("Crazy Egg script loaded")}
        />
      </head>
      <body>
        {!isVariantReady ? (
          // Loading state while waiting for the variant to be ready
          <div style={{ textAlign: "center", marginTop: "50px" }}>
            <p>Loading updated content...</p>
          </div>
        ) : (
          <>
            <Navbar />
            {children}
          </>
        )}
      </body>
    </html>
  );
}
