import Navbar from "@/src/components/Navbar";
import React, { useEffect } from "react";
import "../style/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src="//script.crazyegg.com/pages/scripts/0127/9507.js"
          async
        ></script>

        {/* Inline CSS for flicker prevention */}
        <style>{`
          #ab-content {
            visibility: hidden;
          }
        `}</style>
      </head>
      <body>
        <main id="ab-content">
          {/* Content visibility restored when the page is ready */}
          <script>{`
            document.getElementById('ab-content').style.visibility = 'visible';
          `}</script>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
